// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osfoxirncjvddrnsdqlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zZm94aXJuY2p2ZGRybnNkcWxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1OTI4MDMsImV4cCI6MjA2ODE2ODgwM30.kMlIdL-Byc0elujjHVahF0WEA66u2PwVZi27RDW3lmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});